namespace Snowberry.Globbing.Tests;

/// <summary>
/// Tests for dotfile matching ported from picomatch.
/// </summary>
public class DotfilesTests
{
    // Like picomatch, a leading bracket or extglob that can match "." matches a dotfile even without MatchDotFiles.
    [Theory]
    [InlineData(false, ".js", "*.@(js)", false)]
    [InlineData(true, ".js", "*.@(js)", true)]
    [InlineData(false, ".a", "[.]a", true)]
    [InlineData(true, ".a", "[.]a", true)]
    [InlineData(false, ".foo", "@(.foo)", true)]
    [InlineData(false, ".foo", "!(.)foo", false)]
    public void MatchDotFiles_WithBracketsAndExtglobs(bool matchDotFiles, string input, string pattern, bool expected)
    {
        Glob.IsMatch(input, pattern, new GlobOptions { MatchDotFiles = matchDotFiles }).Should().Be(expected);
    }

    [Theory]
    [InlineData(".a", "*", false)]
    [InlineData("..", "*", false)]
    [InlineData(".a", "**", false)]
    [InlineData("ab", "**", true)]
    [InlineData("abc", "**", true)]
    [InlineData(".ab", "??", false)]
    [InlineData("a/.b", "a/*", false)]
    [InlineData("a/.gitignore", "a/*", false)]
    [InlineData("a/bc", "a/*", true)]
    [InlineData("a/.b", "a/**", false)]
    [InlineData("a/b/.c/d", "a/**", false)]
    [InlineData("a/.b", "*/*", false)]
    [InlineData("a/bc", "*/*", true)]
    [InlineData("a/.b/c", "**/c", false)]
    [InlineData(".a", ".*", true)]
    [InlineData(".gitignore", ".*", true)]
    [InlineData("a", ".*", false)]
    [InlineData(".gitignore", ".gitignore", true)]
    [InlineData(".gitignore", ".git*", true)]
    [InlineData(".gitattributes", ".git*", true)]
    [InlineData("gitignore", ".git*", false)]
    [InlineData("a/.bc", "a/.*", true)]
    [InlineData("a/b", "a/.*", false)]
    [InlineData("a/.b", "**/.*", true)]
    [InlineData("a/b/c", "**/.*", false)]
    [InlineData(".ab", ".??", true)]
    [InlineData("a.b.c", "*.*", true)]
    [InlineData("a", "*.*", false)]
    [InlineData("a.js", "*.js", true)]
    [InlineData("file.test.js", "*.js", true)]
    [InlineData(".js", "*.js", false)]
    [InlineData("a/../b", "*/*/*", false)]
    [InlineData("..", "..", true)]
    [InlineData("a/..", "a/..", true)]
    [InlineData("a/../b", "a/../b", true)]
    [InlineData(".git/config", ".git/*", true)]
    [InlineData(".git/hooks/pre-commit", ".git/**", true)]
    [InlineData(".github/workflows/ci.yml", ".github/**/*.yml", true)]
    [InlineData(".git/config", "**/*", false)]
    [InlineData("a/b/.dot", "**/*dot", false)]
    [InlineData("a/b/.dot", "**/?dot", false)]
    [InlineData("/aaa/.git/foo", "/aaa/**/*", false)]
    [InlineData("/aaa/bbb/.git", "/aaa/bbb/*", false)]
    [InlineData("/aaa/bbb/.git", "/aaa/bbb/**", false)]
    [InlineData("/aaa/bbb/ccc/.git", "/aaa/bbb/**", false)]
    [InlineData("aaa/bbb/.git", "aaa/bbb/**", false)]
    [InlineData("/aaa/bbb/", "/aaa/bbb/**", true)]
    [InlineData("/aaa/bbb/foo", "/aaa/bbb/**", true)]
    [InlineData("foo", "*", true)]
    [InlineData(".foo", "*", false)]
    [InlineData("foo/.bar", "*/*", false)]
    [InlineData("foo/.bar/baz", "*/*/*", false)]
    [InlineData("../.test.js", "../*.js", false)]
    [InlineData(".foo", "**/**", false)]
    [InlineData(".foo", "**", false)]
    [InlineData("foo/.bar", "**/*", false)]
    [InlineData("foo/.bar", "**/*a*", false)]
    [InlineData("foo", "**/.*a*", false)]
    [InlineData(".bar", "**/.*a*", true)]
    [InlineData("foo/.bar", "**/.*a*", true)]
    [InlineData(".foo", "**/.*", true)]
    [InlineData("foo", ".*a*", false)]
    [InlineData(".bar", ".*a*", true)]
    [InlineData("bar", ".*a*", false)]
    [InlineData("foo", ".b*", false)]
    [InlineData(".bar", ".b*", true)]
    [InlineData("bar", ".b*", false)]
    [InlineData("foo", ".*r", false)]
    [InlineData(".bar", ".*r", true)]
    [InlineData("bar", ".*r", false)]
    [InlineData(".dot", "*/*dot", false)]
    [InlineData(".dot", "*/?dot", false)]
    [InlineData(".dot", "*dot", false)]
    [InlineData(".dot", "/*dot", false)]
    [InlineData(".dot", "/?dot", false)]
    [InlineData("/.dot", "/*dot", false)]
    [InlineData("/.dot", "/?dot", false)]
    [InlineData("abc/.dot", "*/*dot", false)]
    [InlineData("abc/.dot", "*/?dot", false)]
    [InlineData("abc/.dot", "abc/*dot", false)]
    [InlineData("abc/abc/.dot", "**/*dot", false)]
    [InlineData("abc/abc/.dot", "**/?dot", false)]
    [InlineData(".dot", "?dot", false)]
    [InlineData("abc/.dot", "abc/?dot", false)]
    [InlineData("../../b", "**/../*", false)]
    [InlineData("../../b", "*/../*", false)]
    [InlineData("../../b", "../*", false)]
    [InlineData("abc", "*/../*", false)]
    [InlineData("abc/../abc", "../*", false)]
    [InlineData("abc/../", "**/../*", false)]
    [InlineData("../b", "../*", true)]
    [InlineData("../../b", "../../*", true)]
    [InlineData("../../..", "../../..", true)]
    [InlineData("../abc", "**/../*", true)]
    [InlineData("../abc", "../*", true)]
    [InlineData("abc/../abc", "**/../*", true)]
    [InlineData("abc/../abc", "*/../*", true)]
    [InlineData("/.dot", "**/.[d]ot", true)]
    [InlineData("aaa/bbb/.dot", "**/.[d]ot", true)]
    [InlineData("aaa/.dot", "*/.[d]ot", true)]
    [InlineData(".dot", ".[d]ot", true)]
    [InlineData("/.dot", "/.[d]ot", true)]
    [InlineData("/.dot", "**/.dot*", true)]
    [InlineData("aaa/bbb/.dot", "**/.dot*", true)]
    [InlineData("aaa/.dot", "*/.dot*", true)]
    [InlineData(".aaa.bbb", ".*.*", true)]
    [InlineData(".aaa.bbb", ".*.bbb", true)]
    [InlineData(".dotfile.js", ".*.js", true)]
    [InlineData(".dot", ".*ot", true)]
    [InlineData(".dot.bbb.ccc", ".*ot.*.*", true)]
    [InlineData(".dot", ".d?t", true)]
    [InlineData(".dot", ".dot*", true)]
    [InlineData("/.dot", "/.dot*", true)]
    [InlineData(".abc/.abc", "**/.abc/**", false)]
    [InlineData(".abc", "**/.abc/**", true)]
    [InlineData("abc/abc/.abc", "**/.abc", true)]
    [InlineData("abc/abc/.abc/c/d/e", "**/.abc/**", true)]
    [InlineData(".editorconfig", ".editorconfig", true)]
    [InlineData(".eslintrc", ".eslintrc", true)]
    [InlineData(".eslintrc.js", ".eslintrc.*", true)]
    [InlineData(".eslintrc.json", ".eslintrc.*", true)]
    [InlineData(".prettierrc", ".prettierrc", true)]
    [InlineData(".env", ".env", true)]
    [InlineData(".env.local", ".env*", true)]
    [InlineData(".env.production", ".env*", true)]
    public void ShouldMatchDotfilesByDefault(string input, string pattern, bool expected)
    {
        Glob.IsMatch(input, pattern).Should().Be(expected);
    }

    [Theory]
    [InlineData(".a", "*", true)]
    [InlineData("abc", "*", true)]
    [InlineData(".a", "**", true)]
    [InlineData("a", "**", true)]
    [InlineData(".ab", "???", true)]
    [InlineData("a/.b", "a/*", true)]
    [InlineData("a/b", "a/*", true)]
    [InlineData("a/.b", "a/**", true)]
    [InlineData("a/b/c", "a/**", true)]
    [InlineData("a/.b", "*/*", true)]
    [InlineData("a/.b/c", "**/c", true)]
    [InlineData("a/b/c", "**/c", true)]
    [InlineData(".js", "*.js", true)]
    [InlineData("..", "*", false)]
    [InlineData("..", "**", false)]
    [InlineData("a/..", "*/*", false)]
    [InlineData(".git/config", "*/*", true)]
    [InlineData(".git/config", "**/*", true)]
    [InlineData(".dot", "**/*dot", true)]
    [InlineData(".dot", "*dot", true)]
    [InlineData(".dot", "?dot", true)]
    [InlineData(".dotfile.js", ".*.js", true)]
    [InlineData("/a/b/.dot", "/**/*dot", true)]
    [InlineData("/a/b/.dot", "**/.[d]ot", true)]
    [InlineData("/a/b/.dot", "**/?dot", true)]
    [InlineData("/a/b/.dot", "/**/.[d]ot", true)]
    [InlineData("/a/b/.dot", "/**/?dot", true)]
    [InlineData("a/b/.dot", "**/*dot", true)]
    [InlineData("a/b/.dot", "**/.[d]ot", true)]
    [InlineData("a/b/.dot", "**/?dot", true)]
    [InlineData("/aaa/.git/foo", "/aaa/**/*", true)]
    [InlineData("/aaa/bbb/.git", "/aaa/bbb/*", true)]
    [InlineData("/aaa/bbb/.git", "/aaa/bbb/**", true)]
    [InlineData("/aaa/bbb/ccc/.git", "/aaa/bbb/**", true)]
    [InlineData("aaa/bbb/.git", "aaa/bbb/**", true)]
    [InlineData("../test.js", "../*.js", true)]
    [InlineData("../.test.js", "../*.js", true)]
    public void ShouldMatchDotfilesWithDotOption(string input, string pattern, bool expected)
    {
        var options = new GlobOptions { MatchDotFiles = true };
        Glob.IsMatch(input, pattern, options).Should().Be(expected);
    }

    [Theory]
    [InlineData("a/b/.dot", "**/*dot", false)]
    [InlineData("a/b/.dot", "**/?dot", false)]
    public void ShouldMatchDotfilesWithDotOptionDisabled(string input, string pattern, bool expected)
    {
        var options = new GlobOptions { MatchDotFiles = false };
        Glob.IsMatch(input, pattern, options).Should().Be(expected);
    }
}