namespace Snowberry.Globbing.Tests;

/// <summary>
/// Tests for invalid (exclusive) dots like .. and . in paths.
/// These should NOT be matched by glob patterns.
/// Ported from: https://github.com/micromatch/picomatch/blob/master/test/dots-invalid.js
/// </summary>
public class DotsInvalidTests
{
    [Theory]
    [InlineData("../abc", "*/*")]
    [InlineData("../abc", "*/abc")]
    [InlineData("../abc", "*/abc/*")]
    [InlineData("../abc", ".*/*")]
    [InlineData("../abc", ".*/abc")]
    [InlineData("../abc", "*./*")]
    [InlineData("../abc", "*./abc")]
    [InlineData("../abc", "**")]
    [InlineData("../abc", "**/abc")]
    [InlineData("../abc", "**/abc/**")]
    [InlineData("../abc", "abc/**")]
    [InlineData("../abc", ".**")]
    [InlineData("../abc", ".**/abc")]
    [InlineData("../abc", "*.*/**")]
    [InlineData("../abc", "*.*/abc")]
    [InlineData("../abc", "**./**")]
    [InlineData("../abc", "**./abc")]
    [InlineData("/../abc", "*/*")]
    [InlineData("/../abc", "/*/*")]
    [InlineData("/../abc", "*/*/*")]
    [InlineData("abc/../abc", "*/*/*")]
    [InlineData("abc/../abc/abc", "*/*/*/*")]
    [InlineData("/../abc", "**")]
    [InlineData("/../abc", "/**/**")]
    [InlineData("abc/../abc", "**/**/**")]
    [InlineData("abc/../abc/abc", "**/**/**/**")]
    [InlineData("abc/..", "*/*")]
    [InlineData("abc/..", "*/*/")]
    [InlineData("abc/..", "*/*/*")]
    [InlineData("abc/../", "*/*")]
    [InlineData("abc/../", "*/*/")]
    [InlineData("abc/../", "*/*/*")]
    [InlineData("abc/../abc/../", "*/*/*/*")]
    [InlineData("abc/../abc/../", "*/*/*/*/")]
    [InlineData("abc/../abc/abc/../", "*/*/*/*/*")]
    [InlineData("abc/..", "**/**")]
    [InlineData("abc/..", "**/**/")]
    [InlineData("abc/../", "**/**")]
    [InlineData("abc/../", "**/**/")]
    [InlineData("abc/../abc/../", "**/**/**/**")]
    [InlineData("abc/../abc/../", "**/**/**/**/")]
    [InlineData("abc/../abc/abc/../", "**/**/**/**/**")]
    [InlineData("./abc", "*")]
    [InlineData("./abc", "*/*")]
    [InlineData("./abc", "*/abc")]
    [InlineData("./abc", "*/abc/*")]
    [InlineData("./abc", ".*/*")]
    [InlineData("./abc", ".*/abc")]
    [InlineData("./abc", "*./*")]
    [InlineData("./abc", "*./abc")]
    [InlineData("./abc", "**")]
    [InlineData("./abc", "**/abc")]
    [InlineData("./abc", "**/abc/**")]
    [InlineData("./abc", "abc/**")]
    [InlineData("/./abc", "*/*")]
    [InlineData("/./abc", "/*/*")]
    [InlineData("/./abc", "*/*/*")]
    [InlineData("abc/./abc", "*/*/*")]
    [InlineData("abc/./abc/abc", "*/*/*/*")]
    [InlineData("/./abc", "**")]
    [InlineData("/./abc", "/**/**")]
    [InlineData("abc/./abc", "**/**/**")]
    [InlineData("abc/./abc/abc", "**/**/**/**")]
    [InlineData("abc/.", "*/*")]
    [InlineData("abc/.", "*/*/")]
    [InlineData("abc/.", "*/*/*")]
    [InlineData("abc/./", "*/*")]
    [InlineData("abc/./", "*/*/")]
    [InlineData("abc/./", "*/*/*")]
    [InlineData("abc/.", "**/**")]
    [InlineData("abc/.", "**/**/")]
    [InlineData("abc/./", "**/**")]
    [InlineData("abc/./", "**/**/")]
    public void ShouldNotMatchInvalidDots(string input, string pattern)
    {
        Glob.IsMatch(input, pattern).Should().BeFalse();
    }

    [Theory]
    [InlineData("../abc", "*/*")]
    [InlineData("../abc", "*/abc")]
    [InlineData("../abc", "**")]
    [InlineData("../abc", "**/abc")]
    [InlineData("/../abc", "*/*")]
    [InlineData("abc/../abc", "*/*/*")]
    [InlineData("/../abc", "**")]
    [InlineData("abc/../abc", "**/**/**")]
    [InlineData("abc/..", "*/*")]
    [InlineData("abc/../", "*/*")]
    [InlineData("abc/..", "**/**")]
    [InlineData("abc/../", "**/**")]
    [InlineData("./abc", "*/*")]
    [InlineData("./abc", "*/abc")]
    [InlineData("./abc", "**")]
    [InlineData("./abc", "**/abc")]
    [InlineData("/./abc", "*/*")]
    [InlineData("abc/./abc", "*/*/*")]
    [InlineData("/./abc", "**")]
    [InlineData("abc/./abc", "**/**/**")]
    [InlineData("abc/.", "*/*")]
    [InlineData("abc/./", "*/*")]
    [InlineData("abc/.", "**/**")]
    [InlineData("abc/./", "**/**")]
    public void ShouldNotMatchInvalidDotsWithBothOptions(string input, string pattern)
    {
        var options = new GlobOptions { MatchDotFiles = true, StrictSlashes = true };
        Glob.IsMatch(input, pattern, options).Should().BeFalse();
    }

    [Theory]
    [InlineData("../abc", "*/*")]
    [InlineData("../abc", "*/abc")]
    [InlineData("../abc", "*/abc/*")]
    [InlineData("../abc", "**")]
    [InlineData("../abc", "**/abc")]
    [InlineData("../abc", "**/abc/**")]
    [InlineData("/../abc", "*/*")]
    [InlineData("/../abc", "/*/*")]
    [InlineData("/../abc", "*/*/*")]
    [InlineData("abc/../abc", "*/*/*")]
    [InlineData("abc/../abc/abc", "*/*/*/*")]
    [InlineData("/../abc", "**")]
    [InlineData("abc/../abc", "**/**/**")]
    [InlineData("abc/..", "*/*")]
    [InlineData("abc/..", "*/*/")]
    [InlineData("abc/..", "*/*/*")]
    [InlineData("abc/../", "*/*")]
    [InlineData("abc/../", "*/*/")]
    [InlineData("abc/..", "**/**")]
    [InlineData("abc/../", "**/**")]
    [InlineData("./abc", "*/*")]
    [InlineData("./abc", "*/abc")]
    [InlineData("./abc", "**")]
    [InlineData("./abc", "**/abc")]
    [InlineData("/./abc", "*/*")]
    [InlineData("/./abc", "/*/*")]
    [InlineData("abc/./abc", "*/*/*")]
    [InlineData("/./abc", "**")]
    [InlineData("abc/./abc", "**/**/**")]
    [InlineData("abc/.", "*/*")]
    [InlineData("abc/.", "*/*/")]
    [InlineData("abc/./", "*/*")]
    [InlineData("abc/.", "**/**")]
    [InlineData("abc/./", "**/**")]
    public void ShouldNotMatchInvalidDotsWithDotOption(string input, string pattern)
    {
        var options = new GlobOptions { MatchDotFiles = true };
        Glob.IsMatch(input, pattern, options).Should().BeFalse();
    }

    [Theory]
    [InlineData("../abc", "*/*")]
    [InlineData("../abc", "*/abc")]
    [InlineData("../abc", "**")]
    [InlineData("../abc", "**/abc")]
    [InlineData("/../abc", "*/*")]
    [InlineData("/../abc", "/*/*")]
    [InlineData("abc/../abc", "*/*/*")]
    [InlineData("/../abc", "**")]
    [InlineData("abc/../abc", "**/**/**")]
    [InlineData("abc/..", "*/*")]
    [InlineData("abc/..", "*/*/")]
    [InlineData("abc/../", "*/*")]
    [InlineData("abc/..", "**/**")]
    [InlineData("abc/../", "**/**")]
    [InlineData("./abc", "*/*")]
    [InlineData("./abc", "*/abc")]
    [InlineData("./abc", "**")]
    [InlineData("./abc", "**/abc")]
    [InlineData("/./abc", "*/*")]
    [InlineData("/./abc", "/*/*")]
    [InlineData("abc/./abc", "*/*/*")]
    [InlineData("/./abc", "**")]
    [InlineData("abc/./abc", "**/**/**")]
    [InlineData("abc/.", "*/*")]
    [InlineData("abc/.", "*/*/")]
    [InlineData("abc/./", "*/*")]
    [InlineData("abc/.", "**/**")]
    [InlineData("abc/./", "**/**")]
    public void ShouldNotMatchInvalidDotsWithStrictSlashesOption(string input, string pattern)
    {
        var options = new GlobOptions { StrictSlashes = true };
        Glob.IsMatch(input, pattern, options).Should().BeFalse();
    }
}