<Project>
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>

    <ItemGroup>
        <PackageVersion Include="AwesomeAssertions" Version="9.6.0" />
        <PackageVersion Include="BenchmarkDotNet" Version="0.15.8" />
        <PackageVersion Include="coverlet.MTP" Version="10.1.0" />
        <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.401" />
        <PackageVersion Include="Microsoft.VisualStudio.DiagnosticsHub.BenchmarkDotNetDiagnosers" Version="18.7.37220.1" />
        <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
        <PackageVersion Include="PolySharp" Version="1.16.0" />
        <PackageVersion Include="System.Memory" Version="4.6.3" />
        <PackageVersion Include="TngTech.ArchUnitNET" Version="0.13.4" />
        <PackageVersion Include="TngTech.ArchUnitNET.xUnitV3" Version="0.13.4" />
        <PackageVersion Include="Testcontainers" Version="4.15.0" />
        <PackageVersion Include="Testcontainers.PostgreSql" Version="4.15.0" />
        <PackageVersion Include="xunit.v3" Version="4.0.1" />
        <PackageVersion Include="StyleCop.Analyzers" Version="1.2.0-beta.556" />
    </ItemGroup>
</Project>
